name: bfast_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyproj  # Always include to avoid PROJ conflicts
  - toml
  - numpy
  - pandas
  - rasterio
  - gdal=3.8.3
  - matplotlib
  - cupy
  - pip
  - pip:
    - git+https://github.com/12rambau/sepal_ui.git@sepal_pre_release
    - git+https://github.com/dfguerrerom/bfast.git
    - git+https://github.com/openforis/earthengine-api.git@v1.1.5rc0#egg=earthengine-api&subdirectory=python
